name: Build Desktop Packages

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch, tag, or commit) to build"
        required: false
        default: ""

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref != '' && github.event.inputs.ref || github.ref }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install fyne-cross
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          go install github.com/fyne-io/fyne-cross@latest
          echo "${HOME}/go/bin" >> $GITHUB_PATH
      - name: Build Windows packages
        run: |
          fyne-cross windows -arch=amd64,386 -app-id=apple.store.helper -name="Apple Store Helper"
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-packages
          path: |
            fyne-cross/dist/windows-*/
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref != '' && github.event.inputs.ref || github.ref }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install Fyne tooling
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          echo "${HOME}/go/bin" >> $GITHUB_PATH
      - name: Build macOS packages
        run: |
          mkdir -p dist/macos
          for arch in amd64 arm64; do
            export GOOS=darwin
            export GOARCH=${arch}
            export CGO_ENABLED=1
            rm -rf "Apple Store Helper.app"
            fyne package -os darwin -appID apple.store.helper -name "Apple Store Helper"
            OUT_DIR="dist/macos/darwin-${arch}"
            mkdir -p "${OUT_DIR}"
            mv "Apple Store Helper.app" "${OUT_DIR}/"
          done
      - name: Fix macOS app signatures
        run: |
          for arch in arm64 amd64; do
            APP_DIR="dist/macos/darwin-${arch}/Apple Store Helper.app"
            if [ -d "$APP_DIR" ]; then
              xattr -cr "$APP_DIR"
              codesign --force --deep --sign - "$APP_DIR"
            fi
          done
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: |
            dist/macos/
